#
# Copyright (C) 2021 TheHitMan7
#

COMMONRELEASE       ?=
COMMONADDONRELEASE  ?=
SPECIFICARCH        ?=

OUT           := out
DIR_R         := BiTGApps-$(SPECIFICARCH)-11.0.0-$(COMMONRELEASE)
DIR_Q         := BiTGApps-$(SPECIFICARCH)-10.0.0-$(COMMONRELEASE)
DIR_PIE       := BiTGApps-$(SPECIFICARCH)-9.0.0-$(COMMONRELEASE)
DIR_OREO      := BiTGApps-$(SPECIFICARCH)-8.1.0-$(COMMONRELEASE)
DIR_OREO_V2   := BiTGApps-$(SPECIFICARCH)-8.0.0-$(COMMONRELEASE)
DIR_NOUGAT    := BiTGApps-$(SPECIFICARCH)-7.1.2-$(COMMONRELEASE)
DIR_NOUGAT_V2 := BiTGApps-$(SPECIFICARCH)-7.1.1-$(COMMONRELEASE)

DIR_ARM32 := BiTGApps-addon-arm-$(COMMONADDONRELEASE)
DIR_ARM64 := BiTGApps-addon-arm64-$(COMMONADDONRELEASE)

DIR_ASSISTANT   := BiTGApps-addon-assistant-$(COMMONADDONRELEASE)
DIR_CALCULATOR  := BiTGApps-addon-calculator-$(COMMONADDONRELEASE)
DIR_CALENDAR    := BiTGApps-addon-calendar-$(COMMONADDONRELEASE)
DIR_CONTACTS    := BiTGApps-addon-contacts-$(COMMONADDONRELEASE)
DIR_DESKCLOCK   := BiTGApps-addon-deskclock-$(COMMONADDONRELEASE)
DIR_DIALER      := BiTGApps-addon-dialer-$(COMMONADDONRELEASE)
DIR_GBOARD      := BiTGApps-addon-gboard-$(COMMONADDONRELEASE)
DIR_MARKUP      := BiTGApps-addon-markup-$(COMMONADDONRELEASE)
DIR_MESSAGES    := BiTGApps-addon-messages-$(COMMONADDONRELEASE)
DIR_PHOTOS      := BiTGApps-addon-photos-$(COMMONADDONRELEASE)
DIR_SOUNDPICKER := BiTGApps-addon-soundpicker-$(COMMONADDONRELEASE)
DIR_VANCED      := BiTGApps-addon-vanced-$(COMMONADDONRELEASE)
DIR_WELLBEING   := BiTGApps-addon-wellbeing-$(COMMONADDONRELEASE)

clean:
	rm -rf "$(OUT)"
	rm -rf "$(DIR_R)"
	rm -rf "$(DIR_Q)"
	rm -rf "$(DIR_PIE)"
	rm -rf "$(DIR_OREO)"
	rm -rf "$(DIR_OREO_V2)"
	rm -rf "$(DIR_NOUGAT)"
	rm -rf "$(DIR_NOUGAT_V2)"
	rm -rf "$(DIR_ARM32)"
	rm -rf "$(DIR_ARM64)"
	rm -rf "$(DIR_ASSISTANT)"
	rm -rf "$(DIR_CALCULATOR)"
	rm -rf "$(DIR_CALENDAR)"
	rm -rf "$(DIR_CONTACTS)"
	rm -rf "$(DIR_DESKCLOCK)"
	rm -rf "$(DIR_DIALER)"
	rm -rf "$(DIR_GBOARD)"
	rm -rf "$(DIR_MARKUP)"
	rm -rf "$(DIR_MESSAGES)"
	rm -rf "$(DIR_PHOTOS)"
	rm -rf "$(DIR_SOUNDPICKER)"
	rm -rf "$(DIR_VANCED)"
	rm -rf "$(DIR_WELLBEING)"
